services:
  - type: web
    name: vijayraj-jewellery
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: "False"
      - key: DB_HOST
        value: "mysql-2a1eba49-heetdarshitsaparia-8ef1.f.aivencloud.com"
      - key: DB_PORT
        value: "26121"
      - key: DB_USER
        value: "avnadmin"
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: "defaultdb"
      - key: DB_SSL
        value: "true"
