"""
Database module for Vijayraj Gems and Jewellery Shop Management System.
Uses PyMySQL with parameterized queries ONLY.
Never string-concatenates SQL.
"""
from contextlib import contextmanager
import pymysql
from pymysql.cursors import DictCursor
from config import Config


def get_connection():
    """Create a new MySQL database connection with DictCursor."""
    kwargs = {
        'host': Config.DB_HOST,
        'port': Config.DB_PORT,
        'user': Config.DB_USER,
        'password': Config.DB_PASSWORD,
        'database': Config.DB_NAME,
        'charset': 'utf8mb4',
        'cursorclass': DictCursor,
        'autocommit': False
    }
    import os
    if os.path.exists('/tmp/mysql.sock'):
        kwargs['unix_socket'] = '/tmp/mysql.sock'
    return pymysql.connect(**kwargs)


def query(sql, params=(), fetchone=False):
    """
    Execute a parameterized SELECT query.
    Always uses parameterized queries to prevent SQL injection.
    """
    conn = get_connection()
    try:
        with conn.cursor() as cur:
            cur.execute(sql, params)
            if fetchone:
                return cur.fetchone()
            return cur.fetchall()
    finally:
        conn.close()


def execute(sql, params=(), commit=True):
    """
    Execute a parameterized INSERT, UPDATE, or DELETE statement.
    Returns (lastrowid, rowcount).
    """
    conn = get_connection()
    try:
        with conn.cursor() as cur:
            cur.execute(sql, params)
            last_id = cur.lastrowid
            affected = cur.rowcount
        if commit:
            conn.commit()
        return last_id, affected
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def callproc(proc_name, params=()):
    """
    Call a MySQL stored procedure safely using parameterized inputs.
    Returns any result sets generated by the procedure.
    """
    conn = get_connection()
    try:
        results = []
        with conn.cursor() as cur:
            cur.callproc(proc_name, params)
            # Fetch primary result set if available
            row = cur.fetchone()
            while row:
                results.append(row)
                row = cur.fetchone()
        conn.commit()
        return results
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


@contextmanager
def transaction():
    """
    Context manager for multi-statement atomic transactions.
    Rolls back automatically on exception, commits on success.
    Usage:
        with transaction() as cur:
            cur.execute("...", (...))
            cur.execute("...", (...))
    """
    conn = get_connection()
    try:
        with conn.cursor() as cur:
            yield cur
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()
