-- ==============================================================================
-- Vijayraj Gems & Jewellery — E-Commerce Seed Data (New Tables Only)
-- ==============================================================================

-- 1. Insert Categories
INSERT INTO `categories` (`name`, `slug`, `description`, `image_path`, `is_active`) VALUES ('Diamond Rings', 'diamond-rings', 'Exquisite diamond rings handcrafted with brilliance and precision.', 'cat-diamond.jpg', 1) ON DUPLICATE KEY UPDATE `description`='Exquisite diamond rings handcrafted with brilliance and precision.', `image_path`='cat-diamond.jpg';
INSERT INTO `categories` (`name`, `slug`, `description`, `image_path`, `is_active`) VALUES ('Crystal Rings', 'crystal-rings', 'Vibrant crystal and gemstone rings radiating timeless elegance.', 'cat-gems.jpg', 1) ON DUPLICATE KEY UPDATE `description`='Vibrant crystal and gemstone rings radiating timeless elegance.', `image_path`='cat-gems.jpg';
INSERT INTO `categories` (`name`, `slug`, `description`, `image_path`, `is_active`) VALUES ('Diamond Necklaces', 'diamond-necklaces', 'Stunning diamond necklaces designed for memorable occasions.', 'cat-diamond.jpg', 1) ON DUPLICATE KEY UPDATE `description`='Stunning diamond necklaces designed for memorable occasions.', `image_path`='cat-diamond.jpg';
INSERT INTO `categories` (`name`, `slug`, `description`, `image_path`, `is_active`) VALUES ('Crystal Necklaces', 'crystal-necklaces', 'Captivating gemstone and crystal statement necklaces.', 'cat-gems.jpg', 1) ON DUPLICATE KEY UPDATE `description`='Captivating gemstone and crystal statement necklaces.', `image_path`='cat-gems.jpg';
INSERT INTO `categories` (`name`, `slug`, `description`, `image_path`, `is_active`) VALUES ('Earrings', 'earrings', 'Timeless studs, drops, and chandeliers in gold, diamond, and silver.', 'cat-gold.jpg', 1) ON DUPLICATE KEY UPDATE `description`='Timeless studs, drops, and chandeliers in gold, diamond, and silver.', `image_path`='cat-gold.jpg';
INSERT INTO `categories` (`name`, `slug`, `description`, `image_path`, `is_active`) VALUES ('Bracelets', 'bracelets', 'Delicate and bold bracelets crafted in premium precious metals.', 'cat-platinum.jpg', 1) ON DUPLICATE KEY UPDATE `description`='Delicate and bold bracelets crafted in premium precious metals.', `image_path`='cat-platinum.jpg';
INSERT INTO `categories` (`name`, `slug`, `description`, `image_path`, `is_active`) VALUES ('Pendants', 'pendants', 'Intricately designed pendants featuring diamonds and precious stones.', 'cat-silver.jpg', 1) ON DUPLICATE KEY UPDATE `description`='Intricately designed pendants featuring diamonds and precious stones.', `image_path`='cat-silver.jpg';
INSERT INTO `categories` (`name`, `slug`, `description`, `image_path`, `is_active`) VALUES ('Jewellery Sets', 'jewellery-sets', 'Coordinated bridal and festive jewellery collections.', 'cat-gold.jpg', 1) ON DUPLICATE KEY UPDATE `description`='Coordinated bridal and festive jewellery collections.', `image_path`='cat-gold.jpg';

-- 2. Backfill existing products with categories, types, stones, specs, and featured (Diamond & Stone Only)
UPDATE `products` SET `name` = 'Diamond Eternity Band', `category` = 'Diamond', `category_id` = 1, `jewellery_type` = 'Ring', `stone_type` = 'Diamond', `specifications` = '18K White Gold with round brilliant diamonds (0.80ct)', `is_featured` = 0, `is_active` = 1 WHERE `id` = 1;
UPDATE `products` SET `name` = 'Diamond Cascade Necklace', `category` = 'Diamond', `category_id` = 3, `jewellery_type` = 'Necklace', `stone_type` = 'Diamond', `specifications` = '18K White Gold, VVS-EF Diamonds 4.50 Carats', `is_featured` = 1, `is_active` = 1 WHERE `id` = 2;
UPDATE `products` SET `name` = 'Sapphire & Diamond Tennis Bracelet', `category` = 'Gems', `category_id` = 6, `jewellery_type` = 'Bracelet', `stone_type` = 'Blue Sapphire', `specifications` = 'Pt950 Platinum with Ceylon Blue Sapphires & Diamonds (3.20ct)', `is_featured` = 0, `is_active` = 1 WHERE `id` = 3;
UPDATE `products` SET `name` = 'Emerald & Diamond Chandelier Earrings', `category` = 'Gems', `category_id` = 5, `jewellery_type` = 'Earrings', `stone_type` = 'Emerald', `specifications` = '18K Yellow Gold with Zambian Emeralds & Diamonds (2.10ct)', `is_featured` = 0, `is_active` = 1 WHERE `id` = 4;
UPDATE `products` SET `name` = 'Royal Navratna Gemstone Collection', `category` = 'Gems', `category_id` = 8, `jewellery_type` = 'Jewellery Set', `stone_type` = 'Precious Gemstones', `specifications` = 'Certified 9-Precious-Gemstones Vedic Suite in 22K Gold', `is_featured` = 1, `is_active` = 1 WHERE `id` = 5;
UPDATE `products` SET `name` = 'Diamond & Polki Bridal Mangalsutra', `category` = 'Diamond', `category_id` = 3, `jewellery_type` = 'Necklace', `stone_type` = 'Diamond', `specifications` = '18K Gold Tanmaniya with VVS Diamonds & Polki (1.10ct)', `is_featured` = 0, `is_active` = 1 WHERE `id` = 6;
UPDATE `products` SET `name` = 'Diamond Cuban Link Chain', `category` = 'Diamond', `category_id` = 3, `jewellery_type` = 'Chain', `stone_type` = 'Diamond', `specifications` = '18K Yellow Gold Cuban link studded with 5.50ct Diamonds', `is_featured` = 0, `is_active` = 1 WHERE `id` = 7;
UPDATE `products` SET `name` = 'Emerald Cut Diamond Pendant', `category` = 'Diamond', `category_id` = 7, `jewellery_type` = 'Pendant', `stone_type` = 'Diamond', `specifications` = '18K White Gold Solitaire Pendant with 1.20ct Emerald Cut Diamond', `is_featured` = 0, `is_active` = 1 WHERE `id` = 8;
UPDATE `products` SET `name` = 'Diamond Studded Gold Bangles', `category` = 'Diamond', `category_id` = 6, `jewellery_type` = 'Bangle', `stone_type` = 'Diamond', `specifications` = 'Set of 2 18K Yellow Gold Bangles with 2.40ct Pavé Diamonds', `is_featured` = 0, `is_active` = 1 WHERE `id` = 9;
UPDATE `products` SET `name` = 'Floral Diamond Nose Pin', `category` = 'Diamond', `category_id` = 5, `jewellery_type` = 'Nose Pin', `stone_type` = 'Diamond', `specifications` = '18K Yellow Gold Floral Diamond Nose Pin (0.08ct)', `is_featured` = 0, `is_active` = 1 WHERE `id` = 10;
UPDATE `products` SET `name` = 'Classic Solitaire Diamond Ring', `category` = 'Diamond', `category_id` = 1, `jewellery_type` = 'Ring', `stone_type` = 'Diamond', `specifications` = '18K Rose Gold Solitaire Ring, 0.75ct Diamond (VVS1/E)', `is_featured` = 1, `is_active` = 1 WHERE `id` = 11;
UPDATE `products` SET `name` = 'Cluster Diamond Drop Earrings', `category` = 'Diamond', `category_id` = 5, `jewellery_type` = 'Earrings', `stone_type` = 'Diamond', `specifications` = '18K White Gold Cluster Diamond Drops, 1.20ct (VS/GH)', `is_featured` = 1, `is_active` = 1 WHERE `id` = 12;
UPDATE `products` SET `name` = '18K Diamond Tennis Bracelet', `category` = 'Diamond', `category_id` = 6, `jewellery_type` = 'Bracelet', `stone_type` = 'Diamond', `specifications` = '18K Yellow Gold Tennis Bracelet, 2.80ct Diamonds', `is_featured` = 1, `is_active` = 1 WHERE `id` = 13;
UPDATE `products` SET `name` = 'Heart Solitaire Diamond Pendant', `category` = 'Diamond', `category_id` = 7, `jewellery_type` = 'Pendant', `stone_type` = 'Diamond', `specifications` = '18K White Gold Infinity Heart Diamond Pendant, 0.40ct', `is_featured` = 0, `is_active` = 1 WHERE `id` = 14;
UPDATE `products` SET `name` = 'Modern Diamond Mangalsutra', `category` = 'Diamond', `category_id` = 3, `jewellery_type` = 'Necklace', `stone_type` = 'Diamond', `specifications` = '18K Yellow Gold Diamond Tanmaniya Mangalsutra, 0.85ct', `is_featured` = 0, `is_active` = 1 WHERE `id` = 15;
UPDATE `products` SET `name` = 'Tanzanite & Diamond Choker Chain', `category` = 'Gems', `category_id` = 4, `jewellery_type` = 'Chain', `stone_type` = 'Tanzanite', `specifications` = '18K White Gold with trillion cut Tanzanite & Diamond accents', `is_featured` = 0, `is_active` = 1 WHERE `id` = 16;
UPDATE `products` SET `name` = 'Natural Emerald Solitaire Ring', `category` = 'Gems', `category_id` = 2, `jewellery_type` = 'Ring', `stone_type` = 'Emerald', `specifications` = '18K Yellow Gold Solitaire Ring with 2.50ct Zambian Emerald', `is_featured` = 0, `is_active` = 1 WHERE `id` = 17;
UPDATE `products` SET `name` = 'Crystal & Diamond Charm Payal', `category` = 'Gems', `category_id` = 6, `jewellery_type` = 'Anklet', `stone_type` = 'Crystal', `specifications` = 'Sterling Silver & Rhodium with Swarovski Crystals and Diamonds', `is_featured` = 0, `is_active` = 1 WHERE `id` = 18;
UPDATE `products` SET `name` = 'Amethyst & Diamond Bangle Set', `category` = 'Gems', `category_id` = 6, `jewellery_type` = 'Bangle', `stone_type` = 'Amethyst', `specifications` = 'Set of 2 18K Rose Gold Bangles with African Amethyst & Diamonds', `is_featured` = 0, `is_active` = 1 WHERE `id` = 19;
UPDATE `products` SET `name` = 'Natural Pearl & Diamond Jhumkas', `category` = 'Gems', `category_id` = 5, `jewellery_type` = 'Earrings', `stone_type` = 'Natural Pearl', `specifications` = 'South Sea Cultured Pearls with 0.90ct Diamonds in 18K Gold', `is_featured` = 0, `is_active` = 1 WHERE `id` = 20;
UPDATE `products` SET `name` = 'Platinum & Diamond Men Band', `category` = 'Diamond', `category_id` = 1, `jewellery_type` = 'Ring', `stone_type` = 'Diamond', `specifications` = 'Pt950 Pure Platinum Brushed Finish Band with Princess Diamond', `is_featured` = 0, `is_active` = 1 WHERE `id` = 21;
UPDATE `products` SET `name` = 'Platinum Diamond Accent Chain', `category` = 'Diamond', `category_id` = 3, `jewellery_type` = 'Chain', `stone_type` = 'Diamond', `specifications` = 'Pt950 Solid Platinum Chain with Station Diamonds', `is_featured` = 0, `is_active` = 1 WHERE `id` = 22;
UPDATE `products` SET `name` = 'Platinum Solitaire Diamond Studs', `category` = 'Diamond', `category_id` = 5, `jewellery_type` = 'Earrings', `stone_type` = 'Diamond', `specifications` = 'Pt950 Platinum Stud Earrings with Certified Diamonds (0.60ct)', `is_featured` = 0, `is_active` = 1 WHERE `id` = 23;
UPDATE `products` SET `name` = 'Platinum & Diamond Link Bracelet', `category` = 'Diamond', `category_id` = 6, `jewellery_type` = 'Bracelet', `stone_type` = 'Diamond', `specifications` = 'Pt950 Platinum & Rose Gold Dual Tone Bracelet with 1.80ct Diamonds', `is_featured` = 0, `is_active` = 1 WHERE `id` = 24;
UPDATE `products` SET `name` = 'Platinum & Blue Sapphire Pendant', `category` = 'Gems', `category_id` = 7, `jewellery_type` = 'Pendant', `stone_type` = 'Blue Sapphire', `specifications` = 'Pt950 Platinum Pendant with Ceylon Sapphire & Central Diamond', `is_featured` = 0, `is_active` = 1 WHERE `id` = 25;
UPDATE `products` SET `name` = 'Natural Yellow Sapphire (Pukhraj)', `category` = 'Gems', `category_id` = 2, `jewellery_type` = 'Gemstone', `stone_type` = 'Yellow Sapphire', `specifications` = 'Natural Unheated Ceylon Yellow Sapphire (Pukhraj) 4.25 Ratti', `is_featured` = 0, `is_active` = 1 WHERE `id` = 26;
UPDATE `products` SET `name` = 'Natural Blue Sapphire (Neelam)', `category` = 'Gems', `category_id` = 2, `jewellery_type` = 'Gemstone', `stone_type` = 'Blue Sapphire', `specifications` = 'Certified Natural Royal Blue Sapphire (Neelam) 5.10 Ratti', `is_featured` = 0, `is_active` = 1 WHERE `id` = 27;
UPDATE `products` SET `name` = 'Burmese Ruby (Manik)', `category` = 'Gems', `category_id` = 2, `jewellery_type` = 'Gemstone', `stone_type` = 'Ruby', `specifications` = 'Natural Burmese Ruby (Manik) Oval Cabochon 3.80 Ratti', `is_featured` = 0, `is_active` = 1 WHERE `id` = 28;
UPDATE `products` SET `name` = 'Colombian Emerald (Panna)', `category` = 'Gems', `category_id` = 2, `jewellery_type` = 'Gemstone', `stone_type` = 'Emerald', `specifications` = 'Zambian Natural Emerald (Panna) Emerald-cut 4.50 Ratti', `is_featured` = 0, `is_active` = 1 WHERE `id` = 29;
UPDATE `products` SET `name` = 'South Sea Pearl & Diamond Necklace', `category` = 'Gems', `category_id` = 4, `jewellery_type` = 'Necklace', `stone_type` = 'Natural Pearl', `specifications` = 'Graduated Natural Saltwater Pearl Strand with Diamond Clasp', `is_featured` = 1, `is_active` = 1 WHERE `id` = 30;
UPDATE `products` SET `name` = 'Ruby & Polki Diamond Choker', `category` = 'Gems', `category_id` = 4, `jewellery_type` = 'Choker', `stone_type` = 'Ruby', `specifications` = '22K Kundan, Polki & Burma Ruby Bridal Choker Suite', `is_featured` = 0, `is_active` = 1 WHERE `id` = 31;
UPDATE `products` SET `name` = 'Kundan & Diamond Kamarbandh', `category` = 'Diamond', `category_id` = 6, `jewellery_type` = 'Waist Chain', `stone_type` = 'Diamond', `specifications` = '18K Gold Bridal Waist Belt with Uncut Diamonds & Rubies', `is_featured` = 0, `is_active` = 1 WHERE `id` = 32;
UPDATE `products` SET `name` = 'Diamond Studded Gold Toe Rings', `category` = 'Diamond', `category_id` = 1, `jewellery_type` = 'Toe Ring', `stone_type` = 'Diamond', `specifications` = 'Pair of 18K Gold Toe Rings with Brilliant Cut Diamonds (0.25ct)', `is_featured` = 0, `is_active` = 1 WHERE `id` = 33;
UPDATE `products` SET `name` = 'Solitaire Diamond Daily Studs', `category` = 'Diamond', `category_id` = 5, `jewellery_type` = 'Studs', `stone_type` = 'Diamond', `specifications` = '18K White Gold Daily Wear Solitaire Diamond Studs (0.50ct)', `is_featured` = 0, `is_active` = 1 WHERE `id` = 34;
UPDATE `products` SET `name` = 'Ruby & Diamond Floral Bracelet', `category` = 'Gems', `category_id` = 6, `jewellery_type` = 'Bracelet', `stone_type` = 'Ruby', `specifications` = '18K Gold Bracelet with Pigeon Blood Rubies and Diamonds', `is_featured` = 0, `is_active` = 1 WHERE `id` = 35;
UPDATE `products` SET `name` = 'Royal Diamond Bridal Choker', `category` = 'Diamond', `category_id` = 3, `jewellery_type` = 'Choker', `stone_type` = 'Diamond', `specifications` = '18K White Gold Cascading Diamond Bridal Choker (8.50ct)', `is_featured` = 0, `is_active` = 1 WHERE `id` = 36;
UPDATE `products` SET `name` = 'Star Diamond Nose Pin', `category` = 'Diamond', `category_id` = 5, `jewellery_type` = 'Nose Pin', `stone_type` = 'Diamond', `specifications` = '18K Yellow Gold Star Diamond Nose Pin (0.08ct)', `is_featured` = 0, `is_active` = 1 WHERE `id` = 37;
UPDATE `products` SET `name` = 'Openable Diamond Kada Bangle', `category` = 'Diamond', `category_id` = 6, `jewellery_type` = 'Bangle', `stone_type` = 'Diamond', `specifications` = '18K Rose Gold Diamond Openable Kada (1.95ct)', `is_featured` = 0, `is_active` = 1 WHERE `id` = 38;
UPDATE `products` SET `name` = 'Mystic Topaz & Diamond Pendant', `category` = 'Gems', `category_id` = 7, `jewellery_type` = 'Pendant', `stone_type` = 'Topaz', `specifications` = '18K White Gold Medallion with Natural Imperial Topaz & Diamonds', `is_featured` = 0, `is_active` = 1 WHERE `id` = 39;
UPDATE `products` SET `name` = 'Royal Ruby & Diamond Brooch', `category` = 'Gems', `category_id` = 7, `jewellery_type` = 'Pendant', `stone_type` = 'Ruby', `specifications` = 'Hand-carved 18K Gold Royal Peacock Brooch with Rubies & Diamonds', `is_featured` = 0, `is_active` = 1 WHERE `id` = 40;
UPDATE `products` SET `name` = 'Natural Chrysoberyl Cat Eye', `category` = 'Gems', `category_id` = 2, `jewellery_type` = 'Gemstone', `stone_type` = 'Cat Eye', `specifications` = 'Natural Chrysoberyl Cat Eye (Lehsunia) with sharp chatoyancy, 4.0 Ratti', `is_featured` = 0, `is_active` = 1 WHERE `id` = 41;
UPDATE `products` SET `name` = 'Certified Italian Red Coral (Moonga)', `category` = 'Gems', `category_id` = 2, `jewellery_type` = 'Gemstone', `stone_type` = 'Red Coral', `specifications` = 'Certified Italian Red Coral (Moonga) Triangular Cut, 5.5 Ratti', `is_featured` = 0, `is_active` = 1 WHERE `id` = 42;
UPDATE `products` SET `name` = 'Natural Hessonite Garnet (Gomed)', `category` = 'Gems', `category_id` = 2, `jewellery_type` = 'Gemstone', `stone_type` = 'Hessonite', `specifications` = 'Natural Ceylon Hessonite Garnet (Gomed) 6.20 Ratti', `is_featured` = 0, `is_active` = 1 WHERE `id` = 43;
UPDATE `products` SET `name` = 'Australian Fire Opal & Diamond Ring', `category` = 'Gems', `category_id` = 2, `jewellery_type` = 'Ring', `stone_type` = 'Opal', `specifications` = 'Natural Australian Fire Opal in 18K Yellow Gold Halo Diamond Setting', `is_featured` = 1, `is_active` = 1 WHERE `id` = 44;
UPDATE `products` SET `name` = 'Natural Matrix Turquoise Pendant', `category` = 'Gems', `category_id` = 7, `jewellery_type` = 'Pendant', `stone_type` = 'Turquoise', `specifications` = 'Tibetan Natural Matrix Turquoise Pendant with Diamond Accents', `is_featured` = 0, `is_active` = 1 WHERE `id` = 45;
UPDATE `products` SET `name` = 'Ruby & Diamond Temple Haram', `category` = 'Gems', `category_id` = 4, `jewellery_type` = 'Necklace', `stone_type` = 'Ruby', `specifications` = '22K Antique Nakshi Haram featuring Lakshmi with Rubies & Polki Diamonds', `is_featured` = 0, `is_active` = 1 WHERE `id` = 46;
UPDATE `products` SET `name` = 'Platinum Diamond Pavé Band', `category` = 'Diamond', `category_id` = 1, `jewellery_type` = 'Ring', `stone_type` = 'Diamond', `specifications` = 'Pt950 Platinum Comfort-Fit Wedding Band with Hidden Diamonds', `is_featured` = 0, `is_active` = 1 WHERE `id` = 47;
UPDATE `products` SET `name` = 'Navratna Gemstone Royal Kada', `category` = 'Gems', `category_id` = 6, `jewellery_type` = 'Bangle', `stone_type` = 'Precious Gemstones', `specifications` = '9-Gemstone Certified Imperial Kada in 18K Gold Setting', `is_featured` = 0, `is_active` = 1 WHERE `id` = 48;
UPDATE `products` SET `name` = '1 Carat IGI Solitaire Diamond Ring', `category` = 'Diamond', `category_id` = 1, `jewellery_type` = 'Ring', `stone_type` = 'Solitaire Diamond', `specifications` = '18K White Gold Classic 6-Prong 1.05ct IGI Certified Solitaire Ring', `is_featured` = 1, `is_active` = 1 WHERE `id` = 49;
UPDATE `products` SET `name` = 'Diamond Evil Eye Nazariya Bracelet', `category` = 'Diamond', `category_id` = 6, `jewellery_type` = 'Bracelet', `stone_type` = 'Diamond', `specifications` = '18K Yellow Gold Nazariya Bracelet with Brilliant Diamonds & Sapphire bead', `is_featured` = 0, `is_active` = 1 WHERE `id` = 50;

-- 2b. Seed Product Images matching diamond and stone items
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (1, 'products/diamond-ring-2.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-ring-2.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (2, 'products/diamond-necklace-1.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-necklace-1.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (3, 'products/diamond-bracelet-1.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-bracelet-1.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (4, 'products/gemstone-earrings.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/gemstone-earrings.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (5, 'products/ruby-ring.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/ruby-ring.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (6, 'products/diamond-necklace-2.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-necklace-2.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (7, 'products/diamond-necklace-1.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-necklace-1.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (8, 'products/diamond-pendant-1.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-pendant-1.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (9, 'products/diamond-bangle.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-bangle.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (10, 'products/diamond-nosepin.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-nosepin.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (11, 'products/diamond-ring-1.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-ring-1.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (12, 'products/diamond-earrings-1.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-earrings-1.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (13, 'products/diamond-bracelet-2.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-bracelet-2.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (14, 'products/diamond-pendant-1.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-pendant-1.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (15, 'products/diamond-necklace-2.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-necklace-2.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (16, 'products/sapphire-pendant.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/sapphire-pendant.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (17, 'products/emerald-ring.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/emerald-ring.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (18, 'products/diamond-bracelet-2.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-bracelet-2.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (19, 'products/diamond-bangle.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-bangle.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (20, 'products/diamond-earrings-2.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-earrings-2.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (21, 'products/diamond-ring-3.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-ring-3.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (22, 'products/diamond-necklace-1.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-necklace-1.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (23, 'products/diamond-earrings-1.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-earrings-1.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (24, 'products/diamond-bracelet-1.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-bracelet-1.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (25, 'products/sapphire-pendant.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/sapphire-pendant.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (26, 'products/gemstone-yellow-sapphire.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/gemstone-yellow-sapphire.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (27, 'products/gemstone-blue-sapphire.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/gemstone-blue-sapphire.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (28, 'products/gemstone-ruby.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/gemstone-ruby.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (29, 'products/gemstone-emerald.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/gemstone-emerald.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (30, 'products/pearl-necklace.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/pearl-necklace.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (31, 'products/ruby-necklace.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/ruby-necklace.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (32, 'products/diamond-choker.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-choker.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (33, 'products/diamond-ring-2.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-ring-2.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (34, 'products/diamond-earrings-1.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-earrings-1.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (35, 'products/ruby-ring.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/ruby-ring.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (36, 'products/diamond-choker.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-choker.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (37, 'products/diamond-nosepin.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-nosepin.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (38, 'products/diamond-bangle.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-bangle.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (39, 'products/sapphire-pendant.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/sapphire-pendant.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (40, 'products/ruby-necklace.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/ruby-necklace.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (41, 'products/gemstone-blue-sapphire.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/gemstone-blue-sapphire.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (42, 'products/gemstone-ruby.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/gemstone-ruby.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (43, 'products/gemstone-yellow-sapphire.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/gemstone-yellow-sapphire.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (44, 'products/opal-ring.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/opal-ring.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (45, 'products/sapphire-pendant.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/sapphire-pendant.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (46, 'products/ruby-necklace.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/ruby-necklace.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (47, 'products/diamond-ring-3.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-ring-3.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (48, 'products/diamond-bangle.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-bangle.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (49, 'products/diamond-solitaire.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-solitaire.jpg';
INSERT INTO `product_images` (`product_id`, `image_path`, `sort_order`, `created_at`) VALUES (50, 'products/diamond-bracelet-2.jpg', 1, NOW()) ON DUPLICATE KEY UPDATE `image_path` = 'products/diamond-bracelet-2.jpg';

-- 3. Seed Demo Customer Account (linked to customer_id = 1)
INSERT INTO `customer_accounts` (`customer_id`, `email`, `password_hash`, `is_active`) VALUES (1, 'demo@customer.com', 'pbkdf2:sha256:1000000$vkN3Sioy3n8zaNNq$7509034e55913d01e7ae4f29c17b221938ea1d4a3984f4c20baaea286ddba6f9', 1) ON DUPLICATE KEY UPDATE `password_hash` = 'pbkdf2:sha256:1000000$vkN3Sioy3n8zaNNq$7509034e55913d01e7ae4f29c17b221938ea1d4a3984f4c20baaea286ddba6f9', `is_active` = 1;

-- 4. Seed Sample Orders, Order Items, Payments, and Status History
INSERT INTO `orders` (`order_no`, `account_id`, `customer_id`, `ship_name`, `ship_phone`, `ship_address`, `ship_city`, `ship_state`, `ship_pincode`, `subtotal`, `gst_percent`, `gst_amount`, `delivery_charge`, `grand_total`, `order_status`, `payment_status`, `invoice_no`, `created_at`) VALUES ('ORD-2026-00001', (SELECT `id` FROM `customer_accounts` WHERE `email`='demo@customer.com'), 1, 'Disha Sherigar', '9876543210', 'Flat 402, Sea Green Heights, Worli Sea Face', 'Mumbai', 'Maharashtra', '400018', 204500.00, 3.00, 6135.00, 0.00, 210635.00, 'Delivered', 'Paid', 'OINV-2026-00001', '2026-09-01 11:30:00') ON DUPLICATE KEY UPDATE `order_status`='Delivered', `payment_status`='Paid';
INSERT INTO `order_items` (`order_id`, `product_id`, `product_name`, `unit_price`, `quantity`, `line_total`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00001'), 11, 'Diamond Ring', 185000.00, 1, 185000.00);
INSERT INTO `order_items` (`order_id`, `product_id`, `product_name`, `unit_price`, `quantity`, `line_total`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00001'), 34, 'Gold Stud Earrings', 19500.00, 1, 19500.00);
INSERT INTO `payments` (`order_id`, `method`, `amount`, `status`, `transaction_ref`, `failure_reason`, `created_at`, `paid_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00001'), 'Card', 210635.00, 'Success', 'TXN-CARD-99201', NULL, '2026-09-01 11:30:00', '2026-09-01 11:32:15');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00001'), 'Pending', NULL, '2026-09-01 11:30:00');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00001'), 'Confirmed', 1, '2026-09-01 11:32:15');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00001'), 'Shipped', 2, '2026-09-02 14:10:00');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00001'), 'Delivered', 2, '2026-09-04 16:45:00');

INSERT INTO `orders` (`order_no`, `account_id`, `customer_id`, `ship_name`, `ship_phone`, `ship_address`, `ship_city`, `ship_state`, `ship_pincode`, `subtotal`, `gst_percent`, `gst_amount`, `delivery_charge`, `grand_total`, `order_status`, `payment_status`, `invoice_no`, `created_at`) VALUES ('ORD-2026-00002', (SELECT `id` FROM `customer_accounts` WHERE `email`='demo@customer.com'), 1, 'Disha Sherigar', '9876543210', 'Flat 402, Sea Green Heights, Worli Sea Face', 'Mumbai', 'Maharashtra', '400018', 55000.00, 3.00, 1650.00, 0.00, 56650.00, 'Delivered', 'Paid', 'OINV-2026-00002', '2026-09-05 15:20:00') ON DUPLICATE KEY UPDATE `order_status`='Delivered', `payment_status`='Paid';
INSERT INTO `order_items` (`order_id`, `product_id`, `product_name`, `unit_price`, `quantity`, `line_total`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00002'), 30, 'Pearl (Moti) Necklace', 55000.00, 1, 55000.00);
INSERT INTO `payments` (`order_id`, `method`, `amount`, `status`, `transaction_ref`, `failure_reason`, `created_at`, `paid_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00002'), 'UPI', 56650.00, 'Success', 'TXN-UPI-88310', NULL, '2026-09-05 15:20:00', '2026-09-05 15:22:04');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00002'), 'Pending', NULL, '2026-09-05 15:20:00');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00002'), 'Confirmed', 1, '2026-09-05 15:22:04');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00002'), 'Shipped', 1, '2026-09-06 10:00:00');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00002'), 'Delivered', 1, '2026-09-08 12:30:00');

INSERT INTO `orders` (`order_no`, `account_id`, `customer_id`, `ship_name`, `ship_phone`, `ship_address`, `ship_city`, `ship_state`, `ship_pincode`, `subtotal`, `gst_percent`, `gst_amount`, `delivery_charge`, `grand_total`, `order_status`, `payment_status`, `invoice_no`, `created_at`) VALUES ('ORD-2026-00003', (SELECT `id` FROM `customer_accounts` WHERE `email`='demo@customer.com'), 1, 'Disha Sherigar', '9876543210', 'Flat 402, Sea Green Heights, Worli Sea Face', 'Mumbai', 'Maharashtra', '400018', 83000.00, 3.00, 2490.00, 0.00, 85490.00, 'Shipped', 'Paid', 'OINV-2026-00003', '2026-09-10 17:15:00') ON DUPLICATE KEY UPDATE `order_status`='Shipped', `payment_status`='Paid';
INSERT INTO `order_items` (`order_id`, `product_id`, `product_name`, `unit_price`, `quantity`, `line_total`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00003'), 4, 'Gold Earrings', 55000.00, 1, 55000.00);
INSERT INTO `order_items` (`order_id`, `product_id`, `product_name`, `unit_price`, `quantity`, `line_total`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00003'), 8, 'Gold Pendant', 28000.00, 1, 28000.00);
INSERT INTO `payments` (`order_id`, `method`, `amount`, `status`, `transaction_ref`, `failure_reason`, `created_at`, `paid_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00003'), 'NetBanking', 85490.00, 'Success', 'TXN-NB-77219', NULL, '2026-09-10 17:15:00', '2026-09-10 17:18:22');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00003'), 'Pending', NULL, '2026-09-10 17:15:00');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00003'), 'Confirmed', 2, '2026-09-10 17:18:22');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00003'), 'Shipped', 2, '2026-09-12 11:20:00');

INSERT INTO `orders` (`order_no`, `account_id`, `customer_id`, `ship_name`, `ship_phone`, `ship_address`, `ship_city`, `ship_state`, `ship_pincode`, `subtotal`, `gst_percent`, `gst_amount`, `delivery_charge`, `grand_total`, `order_status`, `payment_status`, `invoice_no`, `created_at`) VALUES ('ORD-2026-00004', (SELECT `id` FROM `customer_accounts` WHERE `email`='demo@customer.com'), 1, 'Disha Sherigar', '9876543210', 'Flat 402, Sea Green Heights, Worli Sea Face', 'Mumbai', 'Maharashtra', '400018', 155000.00, 3.00, 4650.00, 0.00, 159650.00, 'Confirmed', 'Paid', 'OINV-2026-00004', '2026-09-14 09:40:00') ON DUPLICATE KEY UPDATE `order_status`='Confirmed', `payment_status`='Paid';
INSERT INTO `order_items` (`order_id`, `product_id`, `product_name`, `unit_price`, `quantity`, `line_total`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00004'), 14, 'Diamond Pendant', 155000.00, 1, 155000.00);
INSERT INTO `payments` (`order_id`, `method`, `amount`, `status`, `transaction_ref`, `failure_reason`, `created_at`, `paid_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00004'), 'Card', 159650.00, 'Success', 'TXN-CARD-66120', NULL, '2026-09-14 09:40:00', '2026-09-14 09:42:10');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00004'), 'Pending', NULL, '2026-09-14 09:40:00');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00004'), 'Confirmed', 1, '2026-09-14 09:42:10');

INSERT INTO `orders` (`order_no`, `account_id`, `customer_id`, `ship_name`, `ship_phone`, `ship_address`, `ship_city`, `ship_state`, `ship_pincode`, `subtotal`, `gst_percent`, `gst_amount`, `delivery_charge`, `grand_total`, `order_status`, `payment_status`, `invoice_no`, `created_at`) VALUES ('ORD-2026-00005', (SELECT `id` FROM `customer_accounts` WHERE `email`='demo@customer.com'), 1, 'Disha Sherigar', '9876543210', 'Flat 402, Sea Green Heights, Worli Sea Face', 'Mumbai', 'Maharashtra', '400018', 84000.00, 3.00, 2520.00, 0.00, 86520.00, 'Confirmed', 'Paid', 'OINV-2026-00005', '2026-09-16 13:00:00') ON DUPLICATE KEY UPDATE `order_status`='Confirmed', `payment_status`='Paid';
INSERT INTO `order_items` (`order_id`, `product_id`, `product_name`, `unit_price`, `quantity`, `line_total`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00005'), 44, 'Opal Ring', 42000.00, 1, 42000.00);
INSERT INTO `order_items` (`order_id`, `product_id`, `product_name`, `unit_price`, `quantity`, `line_total`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00005'), 3, 'Silver Bracelet', 42000.00, 1, 42000.00);
INSERT INTO `payments` (`order_id`, `method`, `amount`, `status`, `transaction_ref`, `failure_reason`, `created_at`, `paid_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00005'), 'UPI', 86520.00, 'Success', 'TXN-UPI-55412', NULL, '2026-09-16 13:00:00', '2026-09-16 13:03:00');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00005'), 'Pending', NULL, '2026-09-16 13:00:00');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00005'), 'Confirmed', 3, '2026-09-16 13:03:00');

INSERT INTO `orders` (`order_no`, `account_id`, `customer_id`, `ship_name`, `ship_phone`, `ship_address`, `ship_city`, `ship_state`, `ship_pincode`, `subtotal`, `gst_percent`, `gst_amount`, `delivery_charge`, `grand_total`, `order_status`, `payment_status`, `invoice_no`, `created_at`) VALUES ('ORD-2026-00006', (SELECT `id` FROM `customer_accounts` WHERE `email`='demo@customer.com'), 1, 'Disha Sherigar', '9876543210', 'Flat 402, Sea Green Heights, Worli Sea Face', 'Mumbai', 'Maharashtra', '400018', 35000.00, 3.00, 1050.00, 0.00, 36050.00, 'Cancelled', 'Refunded', 'OINV-2026-00006', '2026-09-18 10:10:00') ON DUPLICATE KEY UPDATE `order_status`='Cancelled', `payment_status`='Refunded';
INSERT INTO `order_items` (`order_id`, `product_id`, `product_name`, `unit_price`, `quantity`, `line_total`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00006'), 1, 'Gold Ring', 35000.00, 1, 35000.00);
INSERT INTO `payments` (`order_id`, `method`, `amount`, `status`, `transaction_ref`, `failure_reason`, `created_at`, `paid_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00006'), 'Card', 36050.00, 'Success', 'TXN-CARD-44199', NULL, '2026-09-18 10:10:00', '2026-09-18 10:12:00');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00006'), 'Pending', NULL, '2026-09-18 10:10:00');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00006'), 'Confirmed', 1, '2026-09-18 10:12:00');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00006'), 'Cancelled', 2, '2026-09-18 15:30:00');

INSERT INTO `orders` (`order_no`, `account_id`, `customer_id`, `ship_name`, `ship_phone`, `ship_address`, `ship_city`, `ship_state`, `ship_pincode`, `subtotal`, `gst_percent`, `gst_amount`, `delivery_charge`, `grand_total`, `order_status`, `payment_status`, `invoice_no`, `created_at`) VALUES ('ORD-2026-00007', (SELECT `id` FROM `customer_accounts` WHERE `email`='demo@customer.com'), 1, 'Disha Sherigar', '9876543210', 'Flat 402, Sea Green Heights, Worli Sea Face', 'Mumbai', 'Maharashtra', '400018', 245000.00, 3.00, 7350.00, 0.00, 252350.00, 'Pending', 'Failed', NULL, '2026-09-20 18:30:00') ON DUPLICATE KEY UPDATE `order_status`='Pending', `payment_status`='Failed';
INSERT INTO `order_items` (`order_id`, `product_id`, `product_name`, `unit_price`, `quantity`, `line_total`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00007'), 12, 'Diamond Earrings', 245000.00, 1, 245000.00);
INSERT INTO `payments` (`order_id`, `method`, `amount`, `status`, `transaction_ref`, `failure_reason`, `created_at`, `paid_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00007'), 'Card', 252350.00, 'Failed', NULL, 'Card issuer declined the transaction (insufficient test funds).', '2026-09-20 18:30:00', '2026-09-20 18:31:45');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00007'), 'Pending', NULL, '2026-09-20 18:30:00');

INSERT INTO `orders` (`order_no`, `account_id`, `customer_id`, `ship_name`, `ship_phone`, `ship_address`, `ship_city`, `ship_state`, `ship_pincode`, `subtotal`, `gst_percent`, `gst_amount`, `delivery_charge`, `grand_total`, `order_status`, `payment_status`, `invoice_no`, `created_at`) VALUES ('ORD-2026-00008', (SELECT `id` FROM `customer_accounts` WHERE `email`='demo@customer.com'), 1, 'Disha Sherigar', '9876543210', 'Flat 402, Sea Green Heights, Worli Sea Face', 'Mumbai', 'Maharashtra', '400018', 85000.00, 3.00, 2550.00, 0.00, 87550.00, 'Pending', 'Failed', NULL, '2026-09-21 12:05:00') ON DUPLICATE KEY UPDATE `order_status`='Pending', `payment_status`='Failed';
INSERT INTO `order_items` (`order_id`, `product_id`, `product_name`, `unit_price`, `quantity`, `line_total`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00008'), 26, 'Yellow Sapphire (Pukhraj)', 85000.00, 1, 85000.00);
INSERT INTO `payments` (`order_id`, `method`, `amount`, `status`, `transaction_ref`, `failure_reason`, `created_at`, `paid_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00008'), 'UPI', 87550.00, 'Failed', NULL, 'UPI simulation failed (failed VPA triggered).', '2026-09-21 12:05:00', '2026-09-21 12:06:30');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00008'), 'Pending', NULL, '2026-09-21 12:05:00');

INSERT INTO `orders` (`order_no`, `account_id`, `customer_id`, `ship_name`, `ship_phone`, `ship_address`, `ship_city`, `ship_state`, `ship_pincode`, `subtotal`, `gst_percent`, `gst_amount`, `delivery_charge`, `grand_total`, `order_status`, `payment_status`, `invoice_no`, `created_at`) VALUES ('ORD-2026-00009', (SELECT `id` FROM `customer_accounts` WHERE `email`='demo@customer.com'), 1, 'Disha Sherigar', '9876543210', 'Flat 402, Sea Green Heights, Worli Sea Face', 'Mumbai', 'Maharashtra', '400018', 9300.00, 3.00, 279.00, 99.00, 9678.00, 'Pending', 'Pending', NULL, '2026-09-22 16:45:00') ON DUPLICATE KEY UPDATE `order_status`='Pending', `payment_status`='Pending';
INSERT INTO `order_items` (`order_id`, `product_id`, `product_name`, `unit_price`, `quantity`, `line_total`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00009'), 17, 'Silver Ring', 5500.00, 1, 5500.00);
INSERT INTO `order_items` (`order_id`, `product_id`, `product_name`, `unit_price`, `quantity`, `line_total`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00009'), 39, 'Silver Pendant', 3800.00, 1, 3800.00);
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00009'), 'Pending', NULL, '2026-09-22 16:45:00');

INSERT INTO `orders` (`order_no`, `account_id`, `customer_id`, `ship_name`, `ship_phone`, `ship_address`, `ship_city`, `ship_state`, `ship_pincode`, `subtotal`, `gst_percent`, `gst_amount`, `delivery_charge`, `grand_total`, `order_status`, `payment_status`, `invoice_no`, `created_at`) VALUES ('ORD-2026-00010', (SELECT `id` FROM `customer_accounts` WHERE `email`='demo@customer.com'), 1, 'Disha Sherigar', '9876543210', 'Flat 402, Sea Green Heights, Worli Sea Face', 'Mumbai', 'Maharashtra', '400018', 8400.00, 3.00, 252.00, 99.00, 8751.00, 'Delivered', 'Paid', 'OINV-2026-00007', '2026-09-23 11:00:00') ON DUPLICATE KEY UPDATE `order_status`='Delivered', `payment_status`='Paid';
INSERT INTO `order_items` (`order_id`, `product_id`, `product_name`, `unit_price`, `quantity`, `line_total`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00010'), 20, 'Silver Earrings', 4200.00, 2, 8400.00);
INSERT INTO `payments` (`order_id`, `method`, `amount`, `status`, `transaction_ref`, `failure_reason`, `created_at`, `paid_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00010'), 'UPI', 8751.00, 'Success', 'TXN-UPI-33109', NULL, '2026-09-23 11:00:00', '2026-09-23 11:02:15');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00010'), 'Pending', NULL, '2026-09-23 11:00:00');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00010'), 'Confirmed', 1, '2026-09-23 11:02:15');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00010'), 'Shipped', 1, '2026-09-23 16:00:00');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00010'), 'Delivered', 1, '2026-09-24 10:30:00');

INSERT INTO `orders` (`order_no`, `account_id`, `customer_id`, `ship_name`, `ship_phone`, `ship_address`, `ship_city`, `ship_state`, `ship_pincode`, `subtotal`, `gst_percent`, `gst_amount`, `delivery_charge`, `grand_total`, `order_status`, `payment_status`, `invoice_no`, `created_at`) VALUES ('ORD-2026-00011', (SELECT `id` FROM `customer_accounts` WHERE `email`='demo@customer.com'), 1, 'Disha Sherigar', '9876543210', 'Flat 402, Sea Green Heights, Worli Sea Face', 'Mumbai', 'Maharashtra', '400018', 550000.00, 3.00, 16500.00, 0.00, 566500.00, 'Confirmed', 'Paid', 'OINV-2026-00008', '2026-09-24 09:15:00') ON DUPLICATE KEY UPDATE `order_status`='Confirmed', `payment_status`='Paid';
INSERT INTO `order_items` (`order_id`, `product_id`, `product_name`, `unit_price`, `quantity`, `line_total`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00011'), 49, 'Diamond Solitaire Ring', 550000.00, 1, 550000.00);
INSERT INTO `payments` (`order_id`, `method`, `amount`, `status`, `transaction_ref`, `failure_reason`, `created_at`, `paid_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00011'), 'NetBanking', 566500.00, 'Success', 'TXN-NB-22904', NULL, '2026-09-24 09:15:00', '2026-09-24 09:18:00');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00011'), 'Pending', NULL, '2026-09-24 09:15:00');
INSERT INTO `order_status_history` (`order_id`, `status`, `changed_by_user_id`, `changed_at`) VALUES ((SELECT `id` FROM `orders` WHERE `order_no`='ORD-2026-00011'), 'Confirmed', 2, '2026-09-24 09:18:00');
